server:
  port: 8087
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: userservice

  datasource:
    url: jdbc:mysql://localhost/factory
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

